FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    python -m spacy download es_core_news_lg

COPY . .

EXPOSE 8080

CMD ["python", "main.py"]
